server:
  port: 8023
  servlet:
    context-path: /EyeconSpring 
 
  ssl:
    key-store-password: 1234
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
#    session:
#      cookie:
#        samesite: None
security:
    require-ssl: true
# database 연동 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cjmy4oq0sxpj.ap-northeast-2.rds.amazonaws.com:3306/test_db
    username: database-1
    password: '!asdf1234'
  mvc:
    static-path-pattern: /static/**
  jpa:
    properties:
      hibernate:
        
        format_sql: true
        use_sql_comments: true
        query:
          in_clause_parameter_padding: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true


      # spring data jpa 설정

impKey: 5741800168864011
impSecretKey: Geqo9oplVUcmtoCti2u8P0OsHTlPaV7NglaaZJyvESM6w7cXlKlJwbLfg2LNFUCuhM76MV7pH49SjhCE
      
application:
  security:
    jwt:
      secret-key: 3498237402398709832750923759823509283750293875098237E3432423423A4A561221ABD2324325FGFGS3535
      expiration: 1800000 # (1800000)30분 access
      refresh-token:
        expiration: 604800000 # 7day refresh